print("SJC23MCA-2056:TESMOL SHAJI")
print("Batch:MCA 2023-25")
import numpy as np
uninitialized_array =np.empty(shape=(2,3))
print("Uninitialized array:")
print(uninitialized_array)
ones_array=np.ones(shape=(2,3))
print("Array with all elements as 1:")
print(ones_array)
zeros_array = np.zeros(shape=(2,3))
print("Array with all elements as 0:")
print(zeros_array)